services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm
    volumes:
      - ..:/workspaces/maged_atl_mock:cached
    command: sleep infinity
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
